language: c

install:
  - wget https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz
  - tar -xzf check-0.12.0.tar.gz
  - pushd check-0.12.0 && ./configure && make && sudo make install && popd

script: make test
